### ISSUE TITLE
:highlights_on for group?

### ISSUE THREAD

**Issue by jmuheim** [jejacks0n/navigasmic#52]
I notice that nobody seems to care about this gem anymore. What a pity.

Anyways, another question: I'd like to use `:highlights_on` on groups: for example when displaying a user, the `users` group should be active, although there is no explicit `show user` item in it.

To compare, the "list users" has a menu entry, so the parent group is highlighted:

![image](https://cloud.githubusercontent.com/assets/1814983/7141822/42397be8-e2d4-11e4-9f4e-9997e50444eb.png)

![image](https://cloud.githubusercontent.com/assets/1814983/7141828/4e249776-e2d4-11e4-904f-ecef5842ae93.png)

But for "show user", there's no entry, so the parent group isn't highlighted:

![image](https://cloud.githubusercontent.com/assets/1814983/7141856/785303ca-e2d4-11e4-9721-cf5b614edaac.png)

![image](https://cloud.githubusercontent.com/assets/1814983/7141862/7f561680-e2d4-11e4-95d0-648229ba5ed5.png)

I know that I can manually assign a `class: 'active'` myself, but this should be possible in an easier way.

**Comment by jejacks0n** [comment]
I still care! ;-p It's really useful when it's needed -- I can't count the number of times that I've seen this built out poorly per project though. So anyway.

You can do complex things with highlights on.. You can do things like just specify the controller (so if most of your actions are within one controller like your example shows). `highlights_on: { controller: "users" }` -- this works similar to how routing works, so if the controller is named `Admin::UsersController`, you would use `highlights_on: { controller: "admin/users" }`.

Additionally, and sometimes better, is to use a regex to capture it by the path that you're on. So let's say everything user nested within a `/users` path prefix. Then you could use `hightlights_on: %r{/users/}`.

Hope that helps.. there's more on that in the readme too.

**Comment by jejacks0n** [comment]
https://github.com/jejacks0n/navigasmic#setting-highlighted--active-states

**Comment by jmuheim** [comment]
Yes, but it doesn't seem to work on `group`s?

**Comment by jejacks0n** [comment]
ah, so you can nest items.. that makes an item into a group more or less -- you can specify no link for the item (or "#") and it becomes a group with all the fanciness of an item.

**Comment by jejacks0n** [comment]
you may have to adjust your css for that.

**Comment by jmuheim** [comment]
I have tried this:

```ruby
= navigation.group User.model_name.human(count: 2), highlights_on: proc { true } do
  ...
```

But this only makes this:

![image](https://cloud.githubusercontent.com/assets/1814983/7146344/3621826e-e2f3-11e4-811d-0a6e13976a7b.png)

By the way:

> I can't count the number of times that I've seen this built out poorly per project though.

You're so right! I have worked with SimpleNavigation before, and feels so clumsy compared to Navigasmic. The thing I love most about Navigasmic is that one can mix items and normal HTML like this:

```slim
- navigation.group user_avatar(t('.user_menu')) do
  - navigation.item "#{fa_icon :user} #{t '.show_account'}", user_registration_path
  - navigation.item "#{fa_icon :edit} #{t '.edit_account'}", edit_user_registration_path

  li
    = link_to destroy_user_session_path, method: :delete do
      = fa_icon('sign-out')
      =< t('.log_out')
```

:+1: :+1: :+1:

**Comment by jejacks0n** [comment]
try this:

```slim
- navigation.item user_avatar(t('.user_menu')), highlights_on: [{ controller: "user" }] do
  - navigation.item "#{fa_icon :user} #{t '.show_account'}", user_registration_path
  - navigation.item "#{fa_icon :edit} #{t '.edit_account'}", edit_user_registration_path
```

**Comment by jmuheim** [comment]
![image](https://cloud.githubusercontent.com/assets/1814983/7146548/9d898630-e2f4-11e4-9bc4-22f56db04a61.png)

**Comment by jmuheim** [comment]
I'm using a helper for achieving this at the moment:

```ruby
  def active_class?(controller_to_check)
    :active if controller_name == controller_to_check.to_s
  end
```

In view:

```slim
- navigation.group User.model_name.human(count: 2), class: active_class?(:users) do
  / ...
```

Still, it would be very nice to be able to use the sophisticated stuff of `highlights_on` on `group` items.

This issue should be reopened in my opinion.

**Comment by jejacks0n** [comment]
Try passing nil or "#" as the first arg in my example. I know for a fact that you can do that.

---
Jeremy Jackson
303-507-6846

**Comment by jmuheim** [comment]
- navigation.group User.model_name.human(count: 2), nil, highlights_on: [{controller: :user}] do

results in

    wrong number of arguments (3 for 0..2)

Am I stupid or what? :stuck_out_tongue_closed_eyes:
