### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by andyundso** [jejacks0n/navigasmic#58]
Hello!

We would like to update our app to Ruby 3.2, but run into the issue reported in #57.

I'm happy to submit a fix, but would need a proper CI setup to check that I break nothing in older Ruby versions. Travis tells that the project no longer exists on their platform, or at least, it is not public.

<img width="712" alt="image" src="https://github.com/jejacks0n/navigasmic/assets/7010698/621c6b1f-e3ae-4ce7-9a44-acd2079d3b22">

Would it be an option to move to GitHub Actions for you? would make it easier for future contributors to run the tests on their fork. also, it's free for public projects.

**Comment by jejacks0n** [comment]
Of course! Thank you for the offer.
